### ISSUE TITLE
Fix app SVG icon colors

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-quest-creator#71]
E.g. the back button on the top left card appears as white, which looks awful on the roleplay cards.

**Comment by toddmedema** [comment]
After some further debugging, looks like the CSS rule to make them white on dark cards is working fine, so might just need a matching rule to make them black by default

```css
@media screen and (min-height: 900px), screen and (min-width: 500px)
<style>…</style>
.base_card.dark .title_container svg {
    color: #fff!important;
}
```
